### ISSUE TITLE
这个 ide 真不错啊，政府还给你发文章呢

### ISSUE THREAD

**Issue by yycmd** [CEC-IDE/OpenCEC-IDE#81]
新闻地址：[http://www.gd.gov.cn/gdywdt/dsdt/content/post_4205291.html](http://www.gd.gov.cn/gdywdt/dsdt/content/post_4205291.html)

> 国内首款适配国产操作系统、自主可控的集成开发环境工具CEC-IDE；国内首款数据安全极限生存保障产品——数据安全守护软硬件一体化产品；国内首款国密指纹认证鼠标……6月20日，广东省数字政府科技创新发展论坛在广州举办，现场发布了6款实现多项全国首创的数字政府科技创新产品。
> 
> 　　本次论坛以“科技创新引领高质量发展”为主题，“我们希望通过此次论坛，搭建科技创新的交流平台，共同探讨科技创新的发展趋势，增强产业发展的信心，助力广东省科技创新高质量发展。”数字广东网络建设有限公司董事长李恒白说。
> 
> 　　“算力就是生产力！算力每投入1元，将带动3—4元GDP增长。”本次论坛上，中国工程院院士郑纬民在《算力——科技创新的基石》的主题演讲中分享了算力发展的新趋势。他说：“人类生产力已从以人力、商力、电力为主的时代进入到以算力为核心生产力的数字经济时代。算力资源增速显著，算力每12个月增长一倍。”
> 
> 　　在谈到算力发展现状时，郑纬民表示，中国在用的数据中心机架总规模超过590万标准机架，服务器规模约2000万台，算力规模超过150E Flops，全球排名第二，且增长速度排名第一。“中国存量算力主要集中在东部地区，其中广东布局鹏城实验室、广州人工智能计算中心等多个计算中心，非常重要。”他说。
> 
> 　　商汤科技智慧城市与商业事业群CTO赵瑞也认同算力的重要性，“未来将从算力、算法和平台范式等方面引发城市智能化、数字化进程的变革。”他说，“AI大模型是通用人工智能的曙光。”
> 
> 　　“为更好应对数字政府时代数据开放带来的安全挑战，我们需要构建统一、协调、有效的数字政府安全保障体系，为数字政府建设纵深推进保驾护航。”工业和信息化部电子第五研究所副所长王蕴辉在进行《筑牢网络和数据安全底座，打造数字政府安全生命线》主题演讲时表示。
> 
> 　　此外，为发挥互补优势、推动资源共享，本次论坛正式启动“守正创新，万马奔腾”计划，首批共21家企业签约入驻，他们将汇聚数字政府公共支撑能力和行业通用业务能力，共同打造技术创新策源地。
> 
> 　　接下来，广东数字政府改革建设将进一步聚焦解决数字政府产业核心技术的“卡脖子”难题，牵住数字关键核心技术自主创新这个“牛鼻子”，强化产业链供应链整合，善用粤港澳大湾区建设形成的人才聚集效应，加快构建起以企业为主体、市场为导向、产学研深度融合的数字政府创新体系，切实提高数字关键核心技术创新能力，持续彰显科技创新示范效应。

![QQ截图20230825112858](https://github.com/CEC-IDE/OpenCEC-IDE/assets/17695132/8a5c11a3-512c-4ac2-bf7d-66df6ad2c5f1)

**Comment by ysh83737** [comment]
恐怖啊，从上到下都在装睡

**Comment by yycmd** [comment]
> 恐怖啊，从上到下都在装睡

要不然经费怎么来

**Comment by yycmd** [comment]
大哥们，去官方的 issues，这是个反串的项目 [https://github.com/microsoft/vscode/issues/191229](https://github.com/microsoft/vscode/issues/191229)
